spring:
  application:
    name: USER-SERVICE
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa :
    hibernate :
      ddl-auto : update
server:
  port: 8089


