spring:
  application:
    name: USER-SERVICE
  datasource:
    url : jdbc:mysql://localhost:3306/UserDb?createDatabaseIfNotExist=true
    username : root
    password :
  jpa :
    hibernate :
      ddl-auto : update
server:
  port: 8089


