spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://user-service-database.crmk6gmiy488.eu-north-1.rds.amazonaws.com:3306/UserDb?createDatabaseIfNotExist=true
    username: root
    password: userDbpwd
  jpa :
    hibernate :
      ddl-auto : update
server:
  port: 8089


